[package]
name = "ANDB"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
dotenv = "0.15.0"
serenity = "0.12.4"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
